security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_SEDE]
    firewalls:
      lonja:
        pattern:     ^/jairo
        provider:    Usuarios
        anonymous:   ~
        form_login: 
          default_target_path: /lonja/
          login_path: /lonja/login
          check_path: /lonja/login_check
        logout:
          path:       lonja_logout
          target:     /lonja/login
    
        remember_me:
           key: cupon1234
           lifetime: 3600
    
    access_control:
      - { path: ^/lonja/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/lonja/*, roles: ROLE_ADMIN }

    providers:
        Usuarios:
         entity: { class: Usuarios\UsuariosBundle\Entity\Usuario, property:email }
    encoders:
         Escalera\BacksedesBundle\Entity\Usuarios: { algorithm: sha512, iterations: 10 }