usuarios_login:
    pattern: /login
    defaults: { _controller: UsuariosBundle:Default:login }
    
usuarios_homepage:
    pattern:  /
    defaults: { _controller: UsuariosBundle:Default:index }

usuarios_login_check:
    pattern:   /login_check
    
usuarios_logout:
    pattern:  /logout

UsuariosBundle_usuario:
    resource: "@UsuariosBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario
